services:
  - type: web
    name: offers-hub-backend
    env: python
    plan: free
    pythonVersion: 3.10.13  # stable, works with greenlet/gevent
    buildCommand: bash -c "pip install --upgrade pip setuptools wheel && pip install -r backend/requirements.txt && playwright install"
    startCommand: python backend/app.py
